### ISSUE TITLE
please provide ipc benchmark report ? 

### ISSUE THREAD

**Issue by rfyiamcool** [siadat/ipc#15]
thank u

**Comment by siadat** [comment]
Hi @rfyiamcool. Thanks for bringing this up. I presume the Go side is very lightweight and the result will probably reflect my kernel's IPC performance. But it's a cool idea indeed. Just two questions:

1. What do you want to measure exactly? Would it be useful if we run send, say, a thousand times and report how long each send operation took on average?

2. Is there any other specific System V IPC benchmark report that you want to eventually compare this to, so I could use as a reference to model my benchmarks after it?
